remote_theme: pmarsceill/just-the-docs


mathjax:
  source: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  config: 'MathJax.Hub.Config({ TeX: {equationNumbers: {autoNumber: "AMS"}}, inlineMath: [ ['$','$'], ["\\(","\\)"] ], processEscapes: true})'
