remote_theme: pmarsceill/just-the-docs

mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({tex: {inlineMath: [['$', '$'], ["\\(", "\\)"]],processEscapes: true,equationNumbers: {autoNumber: "AMS"}}})'
